### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [qmpaas/leadshop#1]
Hey there!

I belong to an open source security research community, and a member (@afkl-cuit) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by qmpaas** [comment]
Sorry for taking so long to recover, I have added SECURITY.md, there is a contact email in it. Thank you

**Comment by JamieSlome** [comment]
@qmpaas - thanks for responding! ⚡ We will get an e-mail sent over shortly.

In the meantime, you can view the report directly [here](https://huntr.dev/bounties/82f8cd2d-3cb5-49a2-b0be-0c0ae510209f/). It is private and only accessible to maintainers with repository write permissions 👍
