### ISSUE TITLE
小程序包找不啊到

### ISSUE THREAD

**Issue by hxer520** [qmpaas/leadshop#5]
如题

**Comment by qmpaas** [comment]
可以去gitee上看看，这里只有主程序

https://gitee.com/leadshop

**Comment by 1665725931** [comment]
一直都有，不知道你咋看的
https://gitee.com/leadshop/applet


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qmpaas/leadshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 下午4:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [qmpaas/leadshop] 小程序包找不啊到 (Issue #5)





 
可以去gitee上看看，这里只有主程序
 
https://gitee.com/leadshop
