### ISSUE TITLE
请问后台源码在哪里？

### ISSUE THREAD

**Issue by LinBaoGe** [qmpaas/leadshop#6]
如题

**Comment by LinBaoGe** [comment]
找不到后台管理admin的源码

**Comment by qmpaas** [comment]
可以去gitee上看看，这里只有主程序

https://gitee.com/leadshop/panel

**Comment by 1665725931** [comment]
问了好几回了你
https://gitee.com/leadshop
你自己找下哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qmpaas/leadshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 中午11:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [qmpaas/leadshop] 请问后台源码在哪里？ (Issue #6)





 
可以去gitee上看看，这里只有主程序
 
https://gitee.com/leadshop/panel
